id: pepsico_registros_medicos
name: RegistrosMedicos
kind: custom
client_id: pepsico
sql_file: pepsico_registros_medicos.sql
output_formats:
- csv
default_recipients: []
params_schema: {}
params_defaults: {}
filename_pattern: '{year}{month}_MD_{report_name}'
description: Informes medicos del segmento pepsico_vulnerables, usuarios activos
